name: Sync University Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Destination Repo
        env:
          DEST_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git push --force https://eduing-in:${DEST_TOKEN}@github.com/eduing-in/eduing-university.git main:main
